Repository LycaniteGroup/Lycanite, pull requests merged in 2020-12, with the labels that each got.

#68 App dev graph
  App/TabTemplate.Designer.cs
  App/TabTemplate.cs
  App/TabTemplate.resx
Labels: App, enhancement

#63 refactor(hashmaps): reworks both hashmaps
  KMDFLycaniteFileFilter/IKashmap.h
  KMDFLycaniteFileFilter/Kashmap.h
Labels: Kernel Mode Driver

#48 Add getter and setter for vhd informations
  VFS/VirtualDisk.cpp
  VFS/VirtualDisk.h
Labels: VFS

#56 Add resizeVirtualDisk
  VFS/DereferencingDisk.cpp
  VFS/DereferencingDisk.h
  VFS/DynamicDisk.cpp
  VFS/DynamicDisk.h
  VFS/FixedDisk.cpp
  VFS/FixedDisk.h
  VFS/VirtualDisk.cpp
  VFS/VirtualDisk.h
Labels: VFS

#72 feature(permissions-map): Permissions map function
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj.filters
  KMDFLycaniteFileFilter/Kashmap.h
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/Utils.h
Labels: Kernel Mode Driver

#75 Add lycanite bridge class to communicate with driver
  App/App.csproj
  App/LycaniteBridge.cs
Labels: App

#76 Merge App dev to master
  App/App.csproj
  App/Form1.Designer.cs
  App/Form1.cs
  App/LycaniteApplication.Designer.cs
  App/LycaniteApplication.cs
  App/LycaniteApplication.resx
  App/LycaniteBridge.cs
  App/Program.cs
  App/Properties/Resources.Designer.cs
  App/Properties/Resources.resx
  App/References/DragAssembly.dll
  App/Resources/close.png
  App/TabController.cs
  App/TabTemplate.Designer.cs
  App/TabTemplate.cs
  App/TabTemplate.resx
  App/packages.config
Labels: Merge Master

#77 Merge Kmd dev to master
  KMD/KMDF Driver.sln
  KMD/KMDFDriver.inf
  KMDFLycaniteFileFilter/.gitignore
  KMDFLycaniteFileFilter/Driver.h
  KMDFLycaniteFileFilter/IKashmap.h
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.inf
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.rc
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj.filters
  KMDFLycaniteFileFilter/Kashmap.h
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/Utils.h
Labels: Merge Master

#78 Merge Vfs dev to master
  VFS/.gitignore
  VFS/DereferencingDisk.cpp
  VFS/DereferencingDisk.h
  VFS/DynamicDisk.cpp
  VFS/DynamicDisk.h
  VFS/FixedDisk.cpp
  VFS/FixedDisk.h
  VFS/VFS.sln
  VFS/VFS.vcxproj
  VFS/VFS.vcxproj.filters
  VFS/VirtualDisk.cpp
  VFS/VirtualDisk.h
Labels: Merge Master

#79 add a UUID Recycler
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.sln
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj.filters
  KMDFLycaniteFileFilter/UUIDRecycler.h
Labels: Kernel Mode Driver

#24 Kernel user space communication
  KMDFLycaniteFileFilter/Driver.h
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/RCa28968
  KMDFLycaniteFileFilter/RCb28968
  KMDFLycaniteFileFilter/RCc28968
Labels: Kernel Mode Driver

#81 refactor(hashmap-uint64): hashmap updated to be used with UINT64 keys
  KMDFLycaniteFileFilter/IKashmap.h
Labels: Kernel Mode Driver

#83 add file permissions manager
  KMDFLycaniteFileFilter/Driver.h
  KMDFLycaniteFileFilter/IKashmap.h
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/Kashmap.h
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/Utils.h
Labels: Kernel Mode Driver

#84 add Event support in LycaniteBridge
  App/LycaniteBridge.cs
Labels: App

#86 App dev
  App/LycaniteBridge.cs
Labels: Merge Master

#85 Kmd dev
  KMDFLycaniteFileFilter/Driver.h
  KMDFLycaniteFileFilter/IKashmap.h
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.sln
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj.filters
  KMDFLycaniteFileFilter/Kashmap.h
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/RCa28968
  KMDFLycaniteFileFilter/RCb28968
  KMDFLycaniteFileFilter/RCc28968
  KMDFLycaniteFileFilter/UUIDRecycler.h
  KMDFLycaniteFileFilter/Utils.h
Labels: Merge Master

#88 Merge Master in KMD-dev
  App/App.csproj
  App/Form1.Designer.cs
  App/Form1.cs
  App/LycaniteApplication.Designer.cs
  App/LycaniteApplication.cs
  App/LycaniteApplication.resx
  App/LycaniteBridge.cs
  App/Program.cs
  App/Properties/Resources.Designer.cs
  App/Properties/Resources.resx
  App/References/DragAssembly.dll
  App/Resources/close.png
  App/TabController.cs
  App/TabTemplate.Designer.cs
  App/TabTemplate.cs
  App/TabTemplate.resx
  App/packages.config
  VFS/.gitignore
  VFS/DereferencingDisk.cpp
  VFS/DereferencingDisk.h
  VFS/DynamicDisk.cpp
  VFS/DynamicDisk.h
  VFS/FixedDisk.cpp
  VFS/FixedDisk.h
  VFS/VFS.sln
  VFS/VFS.vcxproj
  VFS/VFS.vcxproj.filters
  VFS/VirtualDisk.cpp
  VFS/VirtualDisk.h
Labels: Merge Master

#89 Merge master to App Dev branch
  KMD/KMDF Driver.sln
  KMD/KMDFDriver.inf
  KMDFLycaniteFileFilter/.gitignore
  KMDFLycaniteFileFilter/Driver.h
  KMDFLycaniteFileFilter/IKashmap.h
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.inf
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.rc
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.sln
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj.filters
  KMDFLycaniteFileFilter/Kashmap.h
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/RCa28968
  KMDFLycaniteFileFilter/RCb28968
  KMDFLycaniteFileFilter/RCc28968
  KMDFLycaniteFileFilter/UUIDRecycler.h
  KMDFLycaniteFileFilter/Utils.h
  VFS/.gitignore
  VFS/DereferencingDisk.cpp
  VFS/DereferencingDisk.h
  VFS/DynamicDisk.cpp
  VFS/DynamicDisk.h
  VFS/FixedDisk.cpp
  VFS/FixedDisk.h
  VFS/VFS.sln
  VFS/VFS.vcxproj
  VFS/VFS.vcxproj.filters
  VFS/VirtualDisk.cpp
  VFS/VirtualDisk.h
Labels: Merge Master

#90 add device path mapper class
  App/DevicePathMapper.cs
Labels: App

#69 open and close executable
  App/App.csproj
  App/LycaniteApplication.Designer.cs
  App/LycaniteApplication.cs
  App/LycaniteBridge.cs
  App/TabController.cs
  App/TabTemplate.Designer.cs
  App/TabTemplate.cs
  App/TabTemplate.resx
  App/packages.config
  App/runsdvui.cmd
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/Utils.h
Labels: App

#91 Merging App-dev to master
  App/App.csproj
  App/DevicePathMapper.cs
  App/LycaniteApplication.Designer.cs
  App/LycaniteApplication.cs
  App/LycaniteBridge.cs
  App/TabController.cs
  App/TabTemplate.Designer.cs
  App/TabTemplate.cs
  App/TabTemplate.resx
  App/packages.config
  App/runsdvui.cmd
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.c
  KMDFLycaniteFileFilter/KMDFLycaniteFileFilter.vcxproj
  KMDFLycaniteFileFilter/Permissions.h
  KMDFLycaniteFileFilter/Utils.h
Labels: App, Merge Master

#92 App dev add global path
  App/App.csproj
  App/GlobalPathForm.Designer.cs
  App/GlobalPathForm.cs
  App/GlobalPathForm.resx
  App/LycaniteApplication.Designer.cs
  App/LycaniteApplication.cs
  App/LycaniteApplication.resx
  App/LycaniteBridge.cs
  App/TabTemplate.Designer.cs
  App/TabTemplate.resx
Labels: App

#93 Merge master
  App/App.csproj
  App/GlobalPathForm.Designer.cs
  App/GlobalPathForm.cs
  App/GlobalPathForm.resx
  App/LycaniteApplication.Designer.cs
  App/LycaniteApplication.cs
  App/LycaniteApplication.resx
  App/LycaniteBridge.cs
  App/TabTemplate.Designer.cs
  App/TabTemplate.resx
Labels: Merge Master
